baseURL = "https://example.com"
defaultContentLanguage = "en"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]
theme = "hugo-product-launch"
title = "Builders Of The Future, Inc."
[markup.goldmark.renderer]
hardWraps = true
[params]
copyright = "Â© Builders Of The Future, Inc."
description = "You don't even know what we can do for you!"
favicon = "images/favicon.png"
hidedesignbyline = false
images = ["images/share-image.png"]
title = "Builders Of The Future, Inc."
[params.meta]
keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"
